name: Tag on Github
on: [workflow_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}

jobs:
  release:
    name: Tag on Github
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Tag on Github
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          VERSION=$(cat version)
          echo "$VERSION"
          git tag -a "$VERSION" -m "Promoting release $VERSION"
          git push origin "$VERSION"
