name: Tag on Github
on: [workflow_dispatch]

jobs:
  release:
    name: Tag on Github
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Tag on Github
        id: tag_on_github
        run: |
          VERSION=$(cat version)
          echo "$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: "${{ steps.tag_on_github.outputs.version }}",
            })
